### PR TITLE
[1/5] Multi glob trigger

### PR DESCRIPTION
**Pull request by davidhyman**
Updated PR to deal with conflicts introduced in master

### CODE REVIEW

**Comment by alexl0gan** [comment]
Same test is failing on all these PRs

**Comment by davidhyman** [comment]
CI didn't have a user configured for git, now fixed :)

**Comment by davidhyman** [comment]
Can either rebase all the MRs or wait on this one being merged first.

**Comment by acabarbaye** [comment]
@davidhyman is there an order for all the PRs?

**Comment by acabarbaye** [comment]
merged into `master`

**Pull request closed without merging**
